worker_processes 1;
error_log /dev/stderr warn;
pid /run/nginx/nginx.pid;

events { worker_connections 512; }

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;
  access_log    off;
  sendfile      on;
  server_tokens off;
  client_max_body_size 1m;
  keepalive_timeout 30;

  gzip on;
  gzip_types text/css application/javascript application/json image/svg+xml;

  include /etc/nginx/http.d/*.conf;
}
